#include "air780e_mqtt.h"

#include "../common/app_string.h"
#include "ppp_mqtt.h"

/*
 * PPP version adapter.
 *
 * Keep the historical Air780eMqtt_* API so the App protocol layer does not
 * need to change, but all MQTT packets are now generated by the MCU through
 * lwIP PPP. Air780E MQTT AT commands are intentionally not present here.
 */

static char s_ppp_broker_ip[64] = AIR780E_MQTT_BROKER_IP_DEFAULT;
static uint16_t s_ppp_broker_port = AIR780E_MQTT_BROKER_PORT_DEFAULT;
static char s_ppp_client_id[40] = AIR780E_MQTT_CLIENT_ID_DEFAULT;
static char s_ppp_username[40];
static char s_ppp_password[40];
static char s_ppp_will_topic[AIR780E_MQTT_TOPIC_MAX + 1U];
static char s_ppp_will_payload[160];
static int s_ppp_will_retain;
static volatile uint8_t s_ppp_http_active;

void Air780eMqtt_SetBroker(const char *broker_ip, uint16_t port)
{
    AppString_Copy(s_ppp_broker_ip, sizeof(s_ppp_broker_ip), broker_ip);
    s_ppp_broker_port = port;
}

void Air780eMqtt_SetClientId(const char *client_id)
{
    AppString_Copy(s_ppp_client_id, sizeof(s_ppp_client_id), client_id);
}

void Air780eMqtt_SetAuth(const char *username, const char *password)
{
    AppString_Copy(s_ppp_username, sizeof(s_ppp_username), username);
    AppString_Copy(s_ppp_password, sizeof(s_ppp_password), password);
}

void Air780eMqtt_SetWill(const char *topic, const char *payload, int qos, int retain)
{
    (void)qos;
    AppString_Copy(s_ppp_will_topic, sizeof(s_ppp_will_topic), topic);
    AppString_Copy(s_ppp_will_payload, sizeof(s_ppp_will_payload), payload);
    s_ppp_will_retain = retain ? 1 : 0;
}

void Air780eMqtt_EnableLog(int enable)
{
    (void)enable;
}

int Air780eMqtt_AtSelfTest(uint32_t retry_count, uint32_t timeout_ms, uint32_t interval_ms)
{
    (void)retry_count;
    (void)timeout_ms;
    (void)interval_ms;
    return 0;
}

int Air780eMqtt_Connect(void)
{
    if (PppMqtt_IsConnected()) {
        return 0;
    }
    return PppMqtt_Start(s_ppp_broker_ip,
                         s_ppp_broker_port,
                         s_ppp_client_id,
                         s_ppp_username,
                         s_ppp_password,
                         s_ppp_will_topic,
                         s_ppp_will_payload,
                         s_ppp_will_retain);
}

void Air780eMqtt_Disconnect(void)
{
    PppMqtt_Reset();
}

int Air780eMqtt_Pingreq(void)
{
    return PppMqtt_Pingreq();
}

bool Air780eMqtt_IsTcpConnected(void)
{
    return PppMqtt_IsConnected();
}

int Air780eMqtt_GetLastError(void)
{
    return PppMqtt_GetLastError();
}

const char *Air780eMqtt_GetLastErrorString(void)
{
    return PppMqtt_GetLastErrorString();
}

int Air780eMqtt_GetLastConnackRc(void)
{
    return PppMqtt_GetLastConnackRc();
}

int Air780eMqtt_Subscribe(const char *topic, int qos_req)
{
    return PppMqtt_Subscribe(topic, qos_req);
}

int Air780eMqtt_Publish(const char *topic, const char *payload)
{
    if (topic == NULL || payload == NULL) {
        return -1;
    }
    return PppMqtt_Publish(topic, payload, 0);
}

int Air780eMqtt_PublishRetain(const char *topic, const char *payload, int retain)
{
    if (topic == NULL || payload == NULL) {
        return -1;
    }
    return PppMqtt_Publish(topic, payload, retain ? 1 : 0);
}

void Air780eMqtt_SetMessageCallback(Air780eMqtt_MessageCb cb, void *user)
{
    PppMqtt_SetMessageCallback(cb, user);
}

void Air780eMqtt_Service(void)
{
    PppMqtt_Service();
}

uint32_t Air780eMqtt_GetServiceLockMissCount(void)
{
    return 0U;
}

void Air780eMqtt_SetHttpDownloadActive(uint8_t active)
{
    s_ppp_http_active = active ? 1U : 0U;
}

uint8_t Air780eMqtt_IsHttpDownloadActive(void)
{
    return s_ppp_http_active;
}

void Air780eMqtt_ModemSessionLock(void)
{
}

void Air780eMqtt_ModemSessionUnlock(void)
{
}
