"""Generate *_png.h from a PNG file (same style as DJI file2c widget assets)."""
import os
import sys


def gen(png_path, out_path, c_prefix):
    with open(png_path, 'rb') as f:
        data = f.read()
    size = len(data)
    lines = []
    for i in range(0, size, 16):
        chunk = data[i:i + 16]
        hex_vals = ', '.join('0x%02X' % b for b in chunk)
        lines.append('    ' + hex_vals + ',')
    if lines:
        lines[-1] = lines[-1].rstrip(',')

    guard = '__%s_h_included' % c_prefix
    out = [
        '/* Generated by gen_png_header.py, do not edit manually */',
        '#ifndef %s' % guard,
        '#define %s' % guard,
        '',
        '#include <stdint.h>',
        '',
        '/* Contents of file %s */' % os.path.basename(png_path),
        '#define %s_fileName        "%s"' % (c_prefix, os.path.basename(png_path)),
        '#define %s_fileSize        %d' % (c_prefix, size),
        '',
        'static const uint8_t %s_fileBinaryArray[%d] = {' % (c_prefix, size),
        '\n'.join(lines),
        '};',
        '',
        '#endif    /* %s */' % guard,
        '',
    ]
    with open(out_path, 'w', newline='\n') as f:
        f.write('\n'.join(out))
    print('Generated %s (%d bytes)' % (out_path, size))


if __name__ == '__main__':
    if len(sys.argv) != 4:
        print('Usage: gen_png_header.py <input.png> <output.h> <c_prefix>')
        print('Example: gen_png_header.py 1.png route_slot_1_png.h route_slot_1_png')
        sys.exit(1)
    gen(sys.argv[1], sys.argv[2], sys.argv[3])
