"""Generate widget_config_json.h from widget_config.json (file2c replacement).

Usage:
  python gen_widget_binary.py <input.json> <output.h> [symbol_prefix]

If symbol_prefix is given (e.g. cn), symbols become cn_widget_config_json_* so two
configs can be linked in one translation unit.
"""
import sys


def gen(json_path, out_path, symbol_prefix=''):
    with open(json_path, 'rb') as f:
        data = f.read()

    size = len(data)
    lines = []
    for i in range(0, size, 16):
        chunk = data[i:i+16]
        hex_vals = ', '.join('0x%02X' % b for b in chunk)
        lines.append('    ' + hex_vals + ',')
    if lines:
        lines[-1] = lines[-1].rstrip(',')

    array_body = '\n'.join(lines)

    if symbol_prefix:
        guard = '__widget_config_json_%s_h_included' % symbol_prefix
        sym = '%s_' % symbol_prefix
    else:
        guard = '__widget_config_json_h_included'
        sym = ''

    arr_name = '%swidget_config_json_fileBinaryArray' % sym

    out = []
    out.append('/* Generated by tools/gen_widget_binary.py, do not edit manually */')
    out.append('#ifndef %s' % guard)
    out.append('#define %s' % guard)
    out.append('')
    out.append('#include <stdint.h>')
    out.append('')
    out.append('/* Contents of file widget_config.json */')
    out.append('#define {}widget_config_json_fileName        "widget_config.json"'.format(sym))
    out.append('#define {}widget_config_json_fileSize        {}'.format(sym, size))
    out.append('')
    out.append('static const uint8_t %s[%d] = {' % (arr_name, size))
    out.append(array_body)
    out.append('};')
    out.append('')
    out.append('#endif    /* %s */' % guard)
    out.append('')

    with open(out_path, 'w', newline='\n') as f:
        f.write('\n'.join(out))

    print('Generated %s (%d bytes)' % (out_path, size))


if __name__ == '__main__':
    json_path = sys.argv[1]
    out_path = sys.argv[2]
    symbol_prefix = sys.argv[3] if len(sys.argv) > 3 else ''
    gen(json_path, out_path, symbol_prefix)
